plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - readme.md
theme: jekyll-theme-cayman
title: Membuat Development Environment Pribadi dengan VSCode dan Google Cloud
baseurl: "learn-integrating-vscode-with-cloudshell"
url: ""